name: build

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
          fetch-depth: 0

      - name: Delete workflows
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          仓库: ${{ github.repository }}
          retain_days: 0 
          #The number of days that is used to compare with the retention days of each workflow.
          keep_minimum_runs: 2 
          #The minimum runs to keep for each workflow.

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Setup keys
        env:
          private_key: ${{ secrets.ORG_PRIVATE_KEY }}
          public_key: ${{ secrets.ORG_PUBLIC_KEY }}
        run: |
          if [ -z "$private_key" ] || [ -z "$public_key" ]; thenAdd comment更多操作
            echo "Private or public key is not set."
          else
            echo "$private_key" | base64 -d > module/private_key
            echo "$public_key" | base64 -d > module/public_key
          fi
          
      - name: Build with Gradle
        run: |
          echo 'org.gradle.parallel=true' >> gradle.properties
          echo 'org.gradle.vfs.watch=true' >> gradle.properties
          echo 'org.gradle.jvmargs=-Xmx2048m' >> gradle.properties
          sed -i 's/org.gradle.unsafe.configuration-cache=true//g' gradle.properties
          ./gradlew zipRelease

      - name: Prepare artifact
        if: success()
        id: prepareArtifact
        run: |
          releaseName=`ls module/build/outputs/release/ReZygisk-v*-release.zip | awk -F '(/|.zip)' '{print $5}'` && echo "releaseName=$releaseName" >> $GITHUB_OUTPUT
          unzip module/build/outputs/release/ReZygisk-v*-release.zip -d zksu-release
          rm -rf zksu-release/webroot
          
      - name: Upload release
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.prepareArtifact.outputs.releaseName }}
          path: "./zksu-release/*"
